/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauces.sistemanominas.vista;

/**
 *
 * @author daw1
 */
public class DialogoEmpleado extends javax.swing.JDialog {

    /**
     * Creates new form DialogoEmpleado
     */
    public DialogoEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dLDni = new javax.swing.JLabel();
        dLNombre = new javax.swing.JLabel();
        dLTipo = new javax.swing.JLabel();
        dLSalario = new javax.swing.JLabel();
        dLHoras = new javax.swing.JLabel();
        dBAceptar = new javax.swing.JButton();
        dBCancelar = new javax.swing.JButton();
        dTDni = new javax.swing.JTextField();
        dTNombre = new javax.swing.JTextField();
        dTTIpo = new javax.swing.JComboBox<>();
        dTHoras = new javax.swing.JSpinner();
        dTSalario = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dLDni.setText("DNI");

        dLNombre.setText("NOMBRE");

        dLTipo.setText("TIPO");

        dLSalario.setText("SALARIO");

        dLHoras.setText("HORAS");
        setVisible(false);

        dBAceptar.setText("ACEPTAR");
        dBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBAceptarActionPerformed(evt);
            }
        });

        dBCancelar.setText("CANCELAR");
        dBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBCancelarActionPerformed(evt);
            }
        });

        dTTIpo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIJO", "EVENTUAL" }));
        dTTIpo.setSelectedItem("EVENTUAL");
        dTTIpo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dTTIpoItemStateChanged(evt);
            }
        });

        setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dBAceptar)
                        .addGap(56, 56, 56)
                        .addComponent(dBCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dLDni)
                            .addComponent(dLNombre)
                            .addComponent(dLTipo)
                            .addComponent(dLSalario)
                            .addComponent(dLHoras))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dTHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dTDni, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(dTTIpo, 0, 113, Short.MAX_VALUE)
                                .addComponent(dTNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(dTSalario)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLDni)
                    .addComponent(dTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLNombre)
                    .addComponent(dTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLTipo)
                    .addComponent(dTTIpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLSalario)
                    .addComponent(dTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLHoras)
                    .addComponent(dTHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dBAceptar)
                    .addComponent(dBCancelar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBAceptarActionPerformed
        this.pulsadoBotonAceptar(evt);
    }//GEN-LAST:event_dBAceptarActionPerformed

    private void dTTIpoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dTTIpoItemStateChanged
        if (getTipo().equals("FIJO")){
            dLHoras.setVisible(false);
            dTHoras.setVisible(false);
        }
        else{
            dLHoras.setVisible(true);
            dTHoras.setVisible(true);
        }
    }//GEN-LAST:event_dTTIpoItemStateChanged

    private void dBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBCancelarActionPerformed
        this.pulsadoBotonCancelar(evt);
    }//GEN-LAST:event_dBCancelarActionPerformed

    
    private void pulsadoBotonAceptar(java.awt.event.ActionEvent evt) {
        if(this.dTDni.getText().trim().length()>0 && this.dTNombre.getText().trim().length()>0){
        opcion=ACEPTAR;
        setVisible(false);
        }
        
    }                                    

    private void pulsadoBotonCancelar(java.awt.event.ActionEvent evt) {                                      
        opcion=CANCELAR;
        setVisible(false);
    }                                     
    
    
    
    public int mostrar(){
        limpiarCampos();
        opcion=CANCELAR;
        setVisible(true);
        
        return opcion;
    }
    
    public String getDni(){
        return this.dTDni.getText();
    }
    
    public String getNombre(){
        return this.dTNombre.getText();
    }
    public String getTipo(){
        return (String)this.dTTIpo.getSelectedItem();
    }
    
    public float getSalario(){
        return (float)this.dTSalario.getValue();
    }
    
    public int getHoras(){
        return (int)this.dTHoras.getValue();
    }
    
    
    public void limpiarCampos(){
        dTDni.setText("");
        dTNombre.setText("");
        dTSalario.setValue(0.0f);
        dTHoras.setValue(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogoEmpleado(new javax.swing.JFrame(), true).setVisible(true);
                
            }
        });
    }

    public final static int ACEPTAR=1;
    public final static int CANCELAR=0;
    private int opcion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dBAceptar;
    private javax.swing.JButton dBCancelar;
    private javax.swing.JLabel dLDni;
    private javax.swing.JLabel dLHoras;
    private javax.swing.JLabel dLNombre;
    private javax.swing.JLabel dLSalario;
    private javax.swing.JLabel dLTipo;
    private javax.swing.JTextField dTDni;
    private javax.swing.JSpinner dTHoras;
    private javax.swing.JTextField dTNombre;
    private javax.swing.JFormattedTextField dTSalario;
    private javax.swing.JComboBox<String> dTTIpo;
    // End of variables declaration//GEN-END:variables
}
