/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauces.sistemanominas.vista;

import com.sauces.sistemanominas.controlador.Controlador;
import com.sauces.sistemanominas.modelo.Empleado;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author daw1
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        selectorFicheros = new javax.swing.JFileChooser();
        panelDatos = new javax.swing.JPanel();
        lDni = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        lTipo = new javax.swing.JLabel();
        lSalario = new javax.swing.JLabel();
        lIngresos = new javax.swing.JLabel();
        bBorrar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tDni = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tNombre = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tSalario = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tIngresos = new javax.swing.JTextPane();
        lHoras = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tHoras = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tTipo = new javax.swing.JTextPane();
        panelLista = new javax.swing.JPanel();
        bListarEmpleados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        lOrden = new javax.swing.JLabel();
        rDni = new javax.swing.JRadioButton();
        rNombre = new javax.swing.JRadioButton();
        rIngresos = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mArchivoAbrir = new javax.swing.JMenuItem();
        mArchivoGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mEmpleadoNuevo = new javax.swing.JMenuItem();
        mEmpleadoBuscar = new javax.swing.JMenuItem();

        rDni.setActionCommand("DNI");
        rNombre.setActionCommand("NOMBRE");
        rIngresos.setActionCommand("INGRESOS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del empleado"));

        lDni.setText("DNI");

        lNombre.setText("NOMBRE");

        lTipo.setText("TIPO");

        lSalario.setText("SALARIO");

        lIngresos.setText("INGRESOS");

        bBorrar.setText("BORRAR");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bModificar.setText("MODIFICAR");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        tDni.setEditable(false);
        jScrollPane2.setViewportView(tDni);

        jScrollPane3.setViewportView(tNombre);

        jScrollPane4.setViewportView(tSalario);

        tIngresos.setEditable(false);
        jScrollPane5.setViewportView(tIngresos);

        lHoras.setText("HORAS");

        jScrollPane6.setViewportView(tHoras);

        jScrollPane7.setViewportView(tTipo);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(bBorrar)
                        .addGap(44, 44, 44)
                        .addComponent(bModificar))
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelDatosLayout.createSequentialGroup()
                            .addComponent(lIngresos)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane5))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosLayout.createSequentialGroup()
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelDatosLayout.createSequentialGroup()
                                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lDni)
                                        .addComponent(lNombre)
                                        .addComponent(lSalario)
                                        .addComponent(lTipo))
                                    .addGap(28, 28, 28))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                                    .addComponent(lHoras)
                                    .addGap(41, 41, 41)))
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(jScrollPane3)
                                .addComponent(jScrollPane4)
                                .addComponent(jScrollPane6)
                                .addComponent(jScrollPane7)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lDni, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNombre)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTipo))
                .addGap(16, 16, 16)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lSalario)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lHoras))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lIngresos)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBorrar)
                    .addComponent(bModificar))
                .addGap(32, 32, 32))
        );

        panelLista.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de empleados"));

        bListarEmpleados.setText("LISTAR EMPLEADOS");
        bListarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarEmpleadosActionPerformed(evt);
            }
        });

        empleadoTM=new EmpleadoTableModel();
        tablaEmpleados.setModel(empleadoTM);
        tablaEmpleados.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent lse){
                int fila=tablaEmpleados.getSelectedRow();
                if(fila>=0){
                    tDni.setText(tablaEmpleados.getValueAt(fila,0).toString());
                    tNombre.setText((String)tablaEmpleados.getValueAt(fila,1));
                    tSalario.setText(tablaEmpleados.getValueAt(fila,2).toString());
                    tHoras.setText(tablaEmpleados.getValueAt(fila,3).toString());
                    if(tHoras.getText().equals("0")){
                        tTipo.setText("FIJO");
                    }
                    else{
                        tTipo.setText("EVENTUAL");
                    }
                    tIngresos.setText(tablaEmpleados.getValueAt(fila,4).toString());
                }
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);

        lOrden.setText("ORDEN DEL LISTADO:");

        grupoBotones.add(rDni);
        rDni.setText("DNI");
        rDni.setActionCommand("dni");

        grupoBotones.add(rNombre);
        rNombre.setText("NOMBRE");
        rNombre.setActionCommand("nombre");

        grupoBotones.add(rIngresos);
        rIngresos.setText("INGRESOS");
        rIngresos.setActionCommand("ingresos");

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panelListaLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(bListarEmpleados)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelListaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rDni)
                .addGap(39, 39, 39)
                .addComponent(rNombre)
                .addGap(29, 29, 29)
                .addComponent(rIngresos)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bListarEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lOrden)
                    .addComponent(rDni)
                    .addComponent(rNombre)
                    .addComponent(rIngresos))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        mArchivoAbrir.setText("Abrir...");
        mArchivoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mArchivoAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(mArchivoAbrir);

        mArchivoGuardar.setText("Guardar...");
        mArchivoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mArchivoGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mArchivoGuardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Empleado");

        mEmpleadoNuevo.setText("Nuevo...");
        mEmpleadoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmpleadoNuevoActionPerformed(evt);
            }
        });
        jMenu2.add(mEmpleadoNuevo);

        mEmpleadoBuscar.setText("Buscar...");
        mEmpleadoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmpleadoBuscarActionPerformed(evt);
            }
        });
        jMenu2.add(mEmpleadoBuscar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(panelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mEmpleadoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEmpleadoNuevoActionPerformed
        try{
            if(this.dialogo.mostrar()==DialogoEmpleado.ACEPTAR){
                this.tDni.setText(dialogo.getDni());
                this.tNombre.setText(dialogo.getNombre());
                this.tTipo.setText(dialogo.getTipo());
                this.tSalario.setText(Float.toString(dialogo.getSalario()));
                if(dialogo.getTipo().equals("EVENTUAL")){
                    this.tHoras.setText(Integer.toString(dialogo.getHoras()));
                }
                controlador.crearEmpleado();
                this.actualizarTabla();
            }
        } catch (NumberFormatException nfe){
                this.mostrarMensaje("Error en los datos introducidos");
        }
    }//GEN-LAST:event_mEmpleadoNuevoActionPerformed

    private void bListarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarEmpleadosActionPerformed
        controlador.listarEmpleados();
    }//GEN-LAST:event_bListarEmpleadosActionPerformed

    private void mEmpleadoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEmpleadoBuscarActionPerformed
        controlador.buscarEmpleado();
    }//GEN-LAST:event_mEmpleadoBuscarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        int confirmar;
        confirmar=JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este empleado?");
        if(this.tDni.getText().trim().length()>0){
            if(confirmar==JOptionPane.OK_OPTION){
                controlador.eliminarEmpleado();
            }
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        if(this.tDni.getText().trim().length()>0){
            controlador.modificarEmpleado();
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void mArchivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mArchivoAbrirActionPerformed
        if(this.selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.cargarEmpleados();
        }
    }//GEN-LAST:event_mArchivoAbrirActionPerformed

    private void mArchivoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mArchivoGuardarActionPerformed
        if(this.selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.guardarEmpleados();
        }
    }//GEN-LAST:event_mArchivoGuardarActionPerformed

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public String getDni(){
        return this.tDni.getText();
    }
    
    public String getNombre(){
        return this.tNombre.getText();
    }
    
    public String getTipo(){
        return (String)this.tTipo.getText();
    }
    
    public float getSalario(){
        return Float.parseFloat(this.tSalario.getText());
    }
    
    public int getHoras(){
        return Integer.parseInt(this.tHoras.getText());
    }
    
    public float getIngresos(){
        return Float.parseFloat(this.tIngresos.getText());
    }
    
    public String getArchivo(){
        String nombre=selectorFicheros.getSelectedFile().getAbsolutePath();
        return nombre;
    }
    
    public String getOrden(){
        return grupoBotones.getSelection().getActionCommand();
    }
    
    public void mostrarTipo(String tipo){
        tTipo.setText(tipo);
    }
    
    public void mostrarDni(String dni){
        tDni.setText(dni);
    }
    
    public void mostrarNombre(String nombre){
        tNombre.setText(nombre);
    }
    
    public void mostrarSalario(float salario){
        tSalario.setText(String.valueOf(salario));
    }
    
    public void mostrarHoras(int horas){
        tHoras.setText(String.valueOf(horas));
    }
    
    public void mostrarIngresos(float ingresos){
        tIngresos.setText(String.valueOf(ingresos));
    }
    
    public void mostrarEmpleados(List<Empleado> listado){
        empleadoTM.setListado(listado);
        tablaEmpleados.revalidate();
    }
    
    
    public void actualizarTabla(){
        this.tablaEmpleados.revalidate();
    }
    
    public void limpiarCampos(){
        tDni.setText("");
        tNombre.setText("");
        tTipo.setText("");
        tSalario.setText("");
        tHoras.setText("");
        tIngresos.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    private DialogoEmpleado dialogo=new DialogoEmpleado(this,true);
    private Controlador controlador;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bListarEmpleados;
    private javax.swing.JButton bModificar;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lDni;
    private javax.swing.JLabel lHoras;
    private javax.swing.JLabel lIngresos;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lOrden;
    private javax.swing.JLabel lSalario;
    private javax.swing.JLabel lTipo;
    private javax.swing.JMenuItem mArchivoAbrir;
    private javax.swing.JMenuItem mArchivoGuardar;
    private javax.swing.JMenuItem mEmpleadoBuscar;
    private javax.swing.JMenuItem mEmpleadoNuevo;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelLista;
    private javax.swing.JRadioButton rDni;
    private javax.swing.JRadioButton rIngresos;
    private javax.swing.JRadioButton rNombre;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JTextPane tDni;
    private javax.swing.JTextPane tHoras;
    private javax.swing.JTextPane tIngresos;
    private javax.swing.JTextPane tNombre;
    private javax.swing.JTextPane tSalario;
    private javax.swing.JTextPane tTipo;
    private EmpleadoTableModel empleadoTM;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables
}
